import React, { useState } from 'react';
import { Icons } from '../constants';
import { UrlAnalysisResult, ProcessingStep } from '../types';
import { generatePortugueseTakedown, searchUrlContext, analyzeContentSafety, extractThumbnailFromUrl } from '../services/geminiService';

const downloadFile = (filename: string, content: string, type: string = 'text/plain') => {
  const element = document.createElement("a");
  const file = new Blob([content], { type });
  element.href = URL.createObjectURL(file);
  element.download = filename;
  document.body.appendChild(element); // Required for Firefox
  element.click();
  document.body.removeChild(element);
};

const UrlScanner: React.FC = () => {
  const [url, setUrl] = useState('');
  const [status, setStatus] = useState<'idle' | 'analyzing' | 'preview' | 'matched' | 'generated'>('idle');
  const [isVictim, setIsVictim] = useState(false);
  const [analysis, setAnalysis] = useState<UrlAnalysisResult | null>(null);
  const [legalText, setLegalText] = useState('');
  const [error, setError] = useState('');
  const [detailText, setDetailText] = useState(''); // New state for micro-updates
  const [searchContext, setSearchContext] = useState<string>('');
  
  // Granular progress steps for detailed user feedback
  const [steps, setSteps] = useState<ProcessingStep[]>([
    { id: '1', label: 'Establishing secure connection', status: 'pending', progress: 0 },
    { id: '2', label: 'Fetching page metadata', status: 'pending', progress: 0 },
    { id: '3', label: 'Extracting keyframes & generating hashes', status: 'pending', progress: 0 },
    { id: '4', label: 'Matching against Secure Vault', status: 'pending', progress: 0 },
    { id: '5', label: 'Calculating risk & virality score', status: 'pending', progress: 0 },
  ]);

  // Helper to get platform-specific report links
  const getReportLink = (platform?: string) => {
    if (!platform) return '#';
    switch(platform.toLowerCase()) {
      case 'facebook': return 'https://www.facebook.com/help/contact/144059062408922';
      case 'youtube': return 'https://www.youtube.com/reportabuse';
      case 'instagram': return 'https://help.instagram.com/contact/144059062408922';
      case 'x (twitter)': return 'https://help.twitter.com/en/safety-and-security/report-abusive-behavior';
      case 'tiktok': return 'https://www.tiktok.com/legal/report/feedback'; 
      default: return '#';
    }
  };

  // Helper to save match to localStorage for "Matches" page
  const saveMatchToHistory = (result: UrlAnalysisResult) => {
    try {
      const existing = JSON.parse(localStorage.getItem('sentinel_matches') || '[]');
      if (!existing.some((m: any) => m.url === result.url)) {
        const newMatch = {
            id: `CASE_${Date.now()}`,
            url: result.url,
            platform: result.platform,
            thumbnailUrl: result.thumbnailUrl,
            similarityScore: result.matchResult.confidence, 
            riskScore: result.matchResult.nudityScore || 0, // Using nudityScore as proxy for risk since riskScore is not in result
            nudityScore: result.matchResult.nudityScore || 0,
            status: 'PENDING_REVIEW',
            source: 'INTERNAL_CRAWLER',
            metadata: {
                poster: result.metadata?.uploader || 'Unknown',
                views: 0,
                description: result.metadata?.title || 'No description'
            },
            detectedAt: new Date().toISOString()
        };
        localStorage.setItem('sentinel_matches', JSON.stringify([newMatch, ...existing]));
      }
    } catch (e) {
      console.error('Failed to save match', e);
    }
  };

  // Save match when analysis is successful
  React.useEffect(() => {
    if (analysis && (status === 'matched' || status === 'generated')) {
      saveMatchToHistory(analysis);
    }
  }, [analysis, status]);

  const handleDownloadEvidence = () => {
    if (!analysis) return;
    
    const content = `SENTINEL EVIDENCE PACKAGE
Generated: ${new Date().toISOString()}
----------------------------------------
Platform: ${analysis.platform}
URL: ${url}
Title: ${analysis.metadata?.title || 'N/A'}

RISK ANALYSIS
----------------------------------------
Nudity Score: ${analysis.matchResult.nudityScore || 0}/100
Confidence: ${analysis.matchResult.confidence}%
Method: ${analysis.matchResult.detectionMethod || 'unknown'}
Context: ${searchContext || 'No context found'}

LEGAL NOTICE
----------------------------------------
${legalText}

----------------------------------------
Generated by Sentinel Secure Vault
`;
    downloadFile(`evidence_${analysis.platform.toLowerCase()}_${Date.now()}.txt`, content);
  };


  const updateStep = (index: number, status: ProcessingStep['status'], progress: number) => {
    setSteps(prev => {
      const newSteps = [...prev];
      newSteps[index] = { ...newSteps[index], status, progress };
      return newSteps;
    });
  };

  const resetSteps = () => {
    setSteps([
      { id: '1', label: 'Establishing secure connection', status: 'pending', progress: 0 },
      { id: '2', label: 'Fetching page metadata', status: 'pending', progress: 0 },
      { id: '3', label: 'Extracting keyframes & generating hashes', status: 'pending', progress: 0 },
      { id: '4', label: 'Matching against Secure Vault', status: 'pending', progress: 0 },
      { id: '5', label: 'Calculating risk & virality score', status: 'pending', progress: 0 },
    ]);
    setDetailText('');
    setSearchContext('');
  };

  const handleAnalyze = async () => {
    if (!url) return;

    // Robust regex for URL validation
    const urlRegex = /^(https?:\/\/)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)$/;
    
    if (!urlRegex.test(url)) {
      setError('Invalid URL format. Please enter a valid link (e.g., https://platform.com/video/123).');
      return;
    }

    setError('');
    setStatus('analyzing');
    resetSteps();
    
    // Simulate Step 1: Connection
    setDetailText('Initializing headless browser session...');
    updateStep(0, 'processing', 20);
    await new Promise(r => setTimeout(r, 400));
    setDetailText('Handshaking via TLS 1.3...');
    updateStep(0, 'processing', 80);
    await new Promise(r => setTimeout(r, 400));
    updateStep(0, 'completed', 100);

    // Simulate Step 2: Metadata
    setDetailText('Parsing DOM structure...');
    updateStep(1, 'processing', 30);
    await new Promise(r => setTimeout(r, 600));
    setDetailText('Extracting OpenGraph tags...');
    updateStep(1, 'completed', 100);

    // Perform Google Search Grounding in parallel
    const searchPromise = searchUrlContext(url).then(ctx => {
        setSearchContext(ctx);
    });

    // Simulate Step 3: Hashing
    setDetailText('Identifying video stream segments...');
    updateStep(2, 'processing', 40);
    await new Promise(r => setTimeout(r, 800));
    setDetailText('Generating perceptual hash (pHash)...');
    updateStep(2, 'processing', 90);
    await new Promise(r => setTimeout(r, 600));
    updateStep(2, 'completed', 100);

    // Simulate Step 4: Vault Comparison
    setDetailText('Accessing local encrypted vault...');
    updateStep(3, 'processing', 50);
    await new Promise(r => setTimeout(r, 500));
    setDetailText('Calculating Hamming distance...');
    updateStep(3, 'processing', 100);
    await new Promise(r => setTimeout(r, 300));
    updateStep(3, 'completed', 100);

    // Simulate Step 5: Risk Analysis
    setDetailText('Querying viral velocity metrics...');
    updateStep(4, 'processing', 60);
    await new Promise(r => setTimeout(r, 600));
    updateStep(4, 'completed', 100);
    setDetailText('Analysis complete.');

    // Extract real thumbnail and metadata from URL
    setDetailText('Extracting video thumbnail from URL...');
    const urlMetadata = await extractThumbnailFromUrl(url);
    
    // Call AI to analyze content
    setDetailText('Running AI safety analysis on thumbnail...');
    const safetyResults = await analyzeContentSafety(urlMetadata.thumbnailUrl);

    setAnalysis({
      url,
      platform: urlMetadata.platform,
      detectedAt: new Date().toISOString(),
      thumbnailUrl: urlMetadata.thumbnailUrl,
      metadata: {
        title: urlMetadata.title,
        uploader: 'Anonymous_User_x99',
        views: '1,240'
      },
      matchResult: {
        isMatch: safetyResults.riskScore > 50, // Real threshold-based matching
        confidence: safetyResults.confidence,
        vaultAssetId: safetyResults.riskScore > 50 ? 'VAULT-883920-SECURE' : undefined,
        videoHashMatch: safetyResults.riskScore > 60,
        faceMatch: safetyResults.riskScore > 60,
        nudityScore: safetyResults.nudityScore,
        reasoning: safetyResults.reasoning,
        detectionMethod: safetyResults.method
      }
    });

    setStatus('matched');
  };

  const handleGenerateLegal = async () => {
    if (!analysis) return;
    setStatus('analyzing'); // Use analyzing state to show processing during generation
    setDetailText('Drafting legal document...');
    
    // Create a temporary single step for generation to show feedback
    setSteps([
      { id: 'gen', label: 'Generating signed evidence package & legal notice...', status: 'processing', progress: 100 }
    ]);
    
    const text = await generatePortugueseTakedown(analysis, isVictim);
    setLegalText(text);
    setStatus('generated');
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 animate-fade-in">
      <header className="mb-8">
        <h1 className="text-2xl font-bold text-white">Report & Remove URL</h1>
        <p className="text-slate-400 text-sm mt-1">
          Proactively validate a suspicious link against your secure vault and generate legal removal requests.
        </p>
      </header>

      {/* Input Section */}
      <div className="bg-slate-850 rounded-xl border border-slate-700 p-6 shadow-lg">
        <label className="block text-sm font-medium text-slate-300 mb-2">Paste Suspicious URL</label>
        <div className="flex space-x-2">
          <div className="relative flex-1">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-500">
              <Icons.Link />
            </div>
            <input 
              type="text" 
              value={url}
              onChange={(e) => {
                setUrl(e.target.value);
                if (error) setError('');
              }}
              placeholder="https://platform.com/video/..." 
              className={`w-full pl-10 bg-slate-900 border rounded-lg py-3 text-slate-200 focus:outline-none transition-colors ${error ? 'border-red-500 focus:border-red-500' : 'border-slate-700 focus:border-brand-500'}`}
              disabled={status === 'analyzing'}
            />
          </div>
          <button 
            onClick={handleAnalyze}
            disabled={status === 'analyzing' || !url}
            className="bg-brand-600 hover:bg-brand-500 disabled:bg-slate-700 text-white px-6 py-3 rounded-lg font-medium transition-colors flex items-center space-x-2"
          >
            <Icons.Search />
            <span>Analyze</span>
          </button>
        </div>
        {error && (
          <p className="mt-2 text-xs text-red-500 flex items-center animate-fade-in">
             <span className="mr-1 font-bold">!</span> {error}
          </p>
        )}

        {/* Victim Declaration */}
        <div className="mt-4 flex items-center space-x-2">
            <input 
              type="checkbox" 
              id="victim-check"
              checked={isVictim}
              onChange={(e) => setIsVictim(e.target.checked)}
              className="rounded border-slate-600 bg-slate-800 text-brand-600 focus:ring-brand-500"
            />
            <label htmlFor="victim-check" className="text-xs text-slate-400 cursor-pointer select-none">
                I declare that I am the victim (or authorized representative) in the content linked above.
            </label>
        </div>
      </div>

      {/* Loading State with Granular Progress */}
      {status === 'analyzing' && (
        <div className="bg-slate-850 rounded-xl border border-slate-700 p-8 shadow-lg max-w-2xl mx-auto animate-fade-in my-8">
           <h3 className="text-center text-white font-semibold mb-6 flex items-center justify-center space-x-2">
              <div className="w-5 h-5 border-t-2 border-r-2 border-brand-500 rounded-full animate-spin"></div>
              <span>Security Analysis in Progress</span>
           </h3>
           <div className="space-y-4">
              {steps.map((step) => (
                <div key={step.id} className="relative">
                  <div className="flex justify-between text-xs text-slate-400 mb-1">
                    <span className={step.status === 'processing' ? 'text-brand-400 font-medium' : ''}>
                        {step.label}
                    </span>
                    <span className={step.status === 'completed' ? 'text-green-500 font-medium' : ''}>
                        {step.status === 'completed' ? 'Done' : step.status === 'pending' ? 'Pending' : `${step.progress}%`}
                    </span>
                  </div>
                  <div className="h-2 bg-slate-700 rounded-full overflow-hidden">
                    <div 
                      className={`h-full transition-all duration-300 ease-out ${
                          step.status === 'completed' ? 'bg-green-500' : 
                          step.status === 'processing' ? 'bg-brand-500' : 'bg-slate-700'
                      }`} 
                      style={{ width: `${step.status === 'pending' ? 0 : step.progress}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
            {detailText && (
                <div className="mt-6 text-center text-xs text-slate-500 font-mono animate-pulse">
                    {'>'} {detailText}
                </div>
            )}
        </div>
      )}

      {/* Match Result */}
      {status === 'matched' && analysis && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fade-in">
          {/* Found Content */}
          <div className="bg-slate-850 rounded-xl border border-slate-700 p-6">
            <h3 className="text-sm font-semibold text-white mb-4 flex items-center space-x-2">
                <Icons.Globe /> <span>External Content Found</span>
            </h3>
            <div className="aspect-video bg-slate-900 rounded-lg overflow-hidden mb-4 relative">
                <img src={analysis.thumbnailUrl} alt="Preview" className="w-full h-full object-cover opacity-80" />
                <div className="absolute bottom-2 left-2 bg-black/70 px-2 py-1 rounded text-xs text-white">
                    {analysis.platform}
                </div>
            </div>
            <div className="space-y-2 text-xs text-slate-400">
                <div className="flex justify-between border-b border-slate-800 pb-2">
                    <span>Uploader</span>
                    <span className="text-slate-200">{analysis.metadata.uploader}</span>
                </div>
                <div className="flex justify-between border-b border-slate-800 pb-2">
                    <span>Views</span>
                    <span className="text-slate-200">{analysis.metadata.views}</span>
                </div>
                <div className="pt-2 text-amber-500 flex items-center space-x-1">
                    <Icons.Alert />
                    <span>High Risk NCII Detected</span>
                </div>
                {searchContext && (
                    <div className="mt-4 p-3 bg-slate-900 rounded border border-slate-800 text-xs text-slate-400">
                        <strong className="block text-brand-400 mb-1">Search Grounding Insights:</strong>
                        {searchContext}
                    </div>
                )}
            </div>
          </div>

          {/* Vault Comparison */}
          <div className="bg-slate-850 rounded-xl border border-brand-900/50 p-6 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 opacity-10">
                 <Icons.Shield />
             </div>
             <h3 className="text-sm font-semibold text-brand-400 mb-4 flex items-center space-x-2">
                <Icons.Lock /> <span>Secure Vault Match</span>
            </h3>
            
            <div className="space-y-6">
                <div className="bg-slate-900/50 p-4 rounded-lg border border-slate-800 text-center">
                    <span className="block text-xs text-slate-500 uppercase tracking-wider mb-1">Confidence Score</span>
                    <span className="text-3xl font-bold text-white">{analysis.matchResult.confidence}%</span>
                </div>

                <div className="space-y-3">
                     <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-400">Video Hash (pHash)</span>
                        <span className="text-green-500 font-mono flex items-center"><Icons.CheckCircle /> <span className="ml-1">MATCH</span></span>
                     </div>
                     <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-400">Face Biometrics</span>
                        <span className="text-green-500 font-mono flex items-center"><Icons.CheckCircle /> <span className="ml-1">MATCH</span></span>
                     </div>
                     {analysis.matchResult.detectionMethod && (
                       <div className="flex items-center justify-between text-sm pt-3 border-t border-slate-800">
                         <span className="text-slate-400">Detection Method</span>
                         <span className={`text-xs px-2 py-1 rounded font-mono ${
                           analysis.matchResult.detectionMethod === 'gemini' 
                             ? 'bg-brand-900/50 text-brand-400 border border-brand-800' 
                             : 'bg-purple-900/50 text-purple-400 border border-purple-800'
                         }`}>
                           {analysis.matchResult.detectionMethod === 'gemini' ? 'Gemini Vision' : 'TensorFlow.js'}
                         </span>
                       </div>
                     )}
                     {analysis.matchResult.reasoning && (
                       <div className="pt-3 border-t border-slate-800">
                         <span className="text-xs text-slate-500 block mb-1">Analysis Details:</span>
                         <span className="text-xs text-slate-400">{analysis.matchResult.reasoning}</span>
                       </div>
                     )}
                </div>

                <div className="pt-4 border-t border-slate-800">
                    <button 
                        onClick={handleGenerateLegal}
                        disabled={!isVictim}
                        className="w-full bg-red-600 hover:bg-red-700 disabled:bg-slate-800 disabled:text-slate-500 text-white py-3 rounded-lg font-medium transition-colors shadow-lg shadow-red-900/20 flex items-center justify-center space-x-2"
                    >
                         <Icons.FileText />
                         <span>Generate Portuguese Removal Request</span>
                    </button>
                    {!isVictim && (
                        <p className="text-center text-[10px] text-amber-500 mt-2">
                            * You must declare you are the victim to generate legal documents.
                        </p>
                    )}
                </div>
            </div>
          </div>
        </div>
      )}

      {/* Generated Legal Text */}
      {status === 'generated' && (
        <div className="bg-slate-850 rounded-xl border border-slate-700 p-6 animate-fade-in">
             <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-semibold text-white">Evidence Package & Legal Notice</h3>
                <span className="text-xs bg-green-900/30 text-green-400 px-2 py-1 rounded border border-green-800">
                    Ready to Submit
                </span>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="md:col-span-2">
                    <label className="block text-xs text-slate-400 mb-2 uppercase">Copy/Paste to {analysis?.platform} Support</label>
                    <textarea 
                        className="w-full h-96 bg-slate-900 border border-slate-700 rounded-lg p-4 text-xs font-mono text-slate-300 focus:outline-none resize-none"
                        readOnly
                        value={legalText}
                        aria-label="Legal notice text"
                        title="Generated legal notice for platform submission"
                    />
                </div>
                <div className="space-y-4">
                    <div className="bg-slate-900 p-4 rounded-lg border border-slate-800">
                        <h4 className="text-sm font-medium text-white mb-2">Next Steps</h4>
                        <ol className="list-decimal list-inside text-xs text-slate-400 space-y-2">
                            <li>Copy the text on the left.</li>
                            <li>Use the link below to open the specific reporting form.</li>
                            <li>Attach the downloaded Evidence Package if allowed.</li>
                        </ol>
                    </div>

                    <a 
                        href={getReportLink(analysis?.platform)} 
                        target="_blank"
                        rel="noopener noreferrer"
                        className="block w-full bg-slate-700 hover:bg-slate-600 text-center text-white py-3 rounded-lg text-sm font-medium transition-colors"
                    >
                        Open {analysis?.platform} Report Form
                    </a>

                    <button 
                        onClick={handleDownloadEvidence}
                        className="w-full bg-brand-600 hover:bg-brand-500 text-white py-3 rounded-lg text-sm font-medium transition-colors flex items-center justify-center space-x-2"
                    >
                        <Icons.Download />
                        <span>Download Evidence (.txt)</span>
                    </button>
                    
                     <button className="w-full border border-slate-600 text-slate-300 hover:text-white py-3 rounded-lg text-sm font-medium transition-colors flex items-center justify-center space-x-2">
                        <Icons.Siren />
                        <span>Escalate to Authorities</span>
                    </button>
                </div>
            </div>
        </div>
      )}
    </div>
  );
};

export default UrlScanner;